[package]
name = "amiss-adoc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "AsciiDoc reference extraction for the amiss documentation scanner"
exclude.workspace = true

[dependencies]
amiss-wire = { path = "../amiss-wire", version = "0.24.0" }

[lints]
workspace = true
