use amiss_fixtures::{CommitChain, Staged, staged_repository};
use amiss_git::{GitLimits, GitResources, Repository};
use amiss_scan::declared::Declarations;
use amiss_scan::resolve::TargetCache;
use amiss_scan::{Resolution, ScanLimits, ScanResources, SnapshotDiscovery, discover, resolve};
use amiss_wire::model::{Adapter, ObjectFormat, Oid, RepoPath};
use amiss_wire::resolution::{Missing, UnsupportedSemantics};

const DOCS_IGNORE: &[u8] =
    b"# generated by the docs build\n/settings.md\n/rules/\n/*.generated.md\n!/settings.md\n";
const ROOT_IGNORE: &[u8] = b"/build.md\n/docs/tracked.md\ntarget\n";

#[expect(clippy::unwrap_used, reason = "test fixture helper")]
fn fixture() -> CommitChain {
    staged_repository(&[
        (".gitignore", Staged::File(ROOT_IGNORE)),
        ("docs/.gitignore", Staged::File(DOCS_IGNORE)),
        ("docs/index.md", Staged::File(b"# Index\n")),
        ("docs/tracked.md", Staged::File(b"# Tracked\n")),
    ])
    .unwrap()
}

struct Bed {
    repo: Repository,
    git_resources: GitResources,
    scan_resources: ScanResources,
    cache: TargetCache,
    snapshot: SnapshotDiscovery,
    _dir: CommitChain,
}

#[expect(clippy::unwrap_used, reason = "test fixture helper")]
fn bed() -> Bed {
    let dir = fixture();
    let tree = Oid::new(
        ObjectFormat::Sha1,
        dir.commits.first().unwrap().tree.clone(),
    )
    .unwrap();
    let repo = Repository::open(dir.root(), ObjectFormat::Sha1).unwrap();
    let mut git_resources = GitResources::new(GitLimits::CONTRACT);
    let mut scan_resources = ScanResources::new(ScanLimits::CONTRACT);
    let snapshot = discover(
        &repo,
        &mut git_resources,
        &mut scan_resources,
        &amiss_scan::Includes::default(),
        &tree,
    )
    .unwrap();
    Bed {
        repo,
        git_resources,
        scan_resources,
        cache: TargetCache::default(),
        snapshot,
        _dir: dir,
    }
}

impl Bed {
    #[expect(clippy::unwrap_used, reason = "test fixture helper")]
    fn resolve(&mut self, destination: &str) -> Resolution {
        let document = RepoPath::new("docs/index.md".to_owned()).unwrap();
        resolve(
            &self.repo,
            &mut self.git_resources,
            &mut self.scan_resources,
            &mut self.cache,
            &self.snapshot,
            None,
            Adapter::Markdown,
            &document,
            false,
            destination,
        )
        .unwrap()
        .1
    }
}

fn declared_by(resolution: &Resolution) -> Option<String> {
    match resolution {
        Resolution::DeclaredUntracked(declared) => Some(format!(
            "{}|{}",
            String::from_utf8_lossy(declared.path.as_bytes()),
            String::from_utf8_lossy(declared.declared_by.as_bytes()),
        )),
        Resolution::Resolved(_)
        | Resolution::Missing(_)
        | Resolution::TypeMismatch(_)
        | Resolution::UnsupportedTarget(_)
        | Resolution::UnsupportedSemantics(_)
        | Resolution::UnsupportedVersion(_)
        | Resolution::Invalid(_)
        | Resolution::External(_) => None,
    }
}

#[test]
fn an_anchored_literal_line_declares_exactly_its_own_path() {
    let declarations = Declarations::parse(b"/settings.md\n");
    assert!(declarations.declares(b"settings.md"));
    assert!(!declarations.declares(b"settings.markdown"));
    assert!(!declarations.declares(b"sub/settings.md"));
}

#[test]
fn a_directory_line_answers_for_its_descendants_and_itself() {
    let declarations = Declarations::parse(b"/rules/\n");
    assert!(declarations.declares(b"rules"));
    assert!(declarations.declares(b"rules/E501.md"));
    assert!(declarations.declares(b"rules/deep/E501.md"));
    assert!(!declarations.declares(b"rules.md"));
    assert!(!declarations.declares(b"other/rules/E501.md"));
}

#[test]
fn every_line_that_could_clear_more_than_it_names_is_refused() {
    for line in [
        &b"/*.md\n"[..],
        b"/rules/*\n",
        b"/settings.?d\n",
        b"/[abc].md\n",
        b"!/settings.md\n",
        b"# /settings.md\n",
        b"docs/settings.md\n",
        b"settings.md\n",
        b"/a\\b.md\n",
        b"/../escape.md\n",
        b"/./here.md\n",
        b"/a//b.md\n",
        b"/\n",
        b"\n",
    ] {
        let declarations = Declarations::parse(line);
        for probe in [&b"settings.md"[..], b"rules", b"rules/E501.md", b"a/b.md"] {
            assert!(
                !declarations.declares(probe),
                "{} declared {}",
                String::from_utf8_lossy(line),
                String::from_utf8_lossy(probe),
            );
        }
    }
}

#[test]
fn a_line_survives_the_spellings_a_text_editor_leaves_behind() {
    assert!(Declarations::parse(b"/settings.md   \t\r\n").declares(b"settings.md"));
    assert!(Declarations::parse(b"/settings.md").declares(b"settings.md"));
    let many = Declarations::parse(b"/a.md\r\n\r\n/b/\n\n/c.md");
    assert!(many.declares(b"a.md"));
    assert!(many.declares(b"b/deep.md"));
    assert!(many.declares(b"c.md"));
}

#[test]
fn a_declared_absent_target_names_the_file_that_declared_it() {
    let mut bed = bed();
    assert_eq!(
        declared_by(&bed.resolve("settings.md")).as_deref(),
        Some("docs/settings.md|docs/.gitignore"),
    );
    assert_eq!(
        declared_by(&bed.resolve("rules/E501.md")).as_deref(),
        Some("docs/rules/E501.md|docs/.gitignore"),
    );
    assert_eq!(
        declared_by(&bed.resolve("../build.md")).as_deref(),
        Some("build.md|.gitignore"),
        "an ancestor ignore file answers for a path no nearer one names",
    );
}

#[test]
fn nothing_a_declaration_cannot_name_stops_being_missing() {
    let mut bed = bed();
    for destination in [
        "missing.md",
        "page.generated.md",
        "rules.md",
        "sub/other.md",
    ] {
        assert!(
            matches!(
                bed.resolve(destination),
                Resolution::Missing(Missing::PathNotFound { .. })
            ),
            "{destination} was not reported missing",
        );
    }
}

#[test]
fn a_tracked_target_resolves_though_an_ignore_file_names_it() {
    let mut bed = bed();
    assert!(
        matches!(bed.resolve("tracked.md"), Resolution::Resolved(_)),
        "an ignore line must not answer for a path the tree holds",
    );
}

#[test]
fn a_target_awaiting_a_build_time_attribute_is_declared_rather_than_missed() {
    let mut bed = bed();
    let document = RepoPath::new("docs/index.md".to_owned()).expect("document path");
    let attribute = resolve(
        &bed.repo,
        &mut bed.git_resources,
        &mut bed.scan_resources,
        &mut bed.cache,
        &bed.snapshot,
        None,
        Adapter::AsciiDoc,
        &document,
        false,
        "{includedir}/shared.adoc",
    )
    .expect("resolution")
    .1;
    assert!(matches!(
        attribute,
        Resolution::UnsupportedSemantics(UnsupportedSemantics::AttributeDependent)
    ));

    let markdown = resolve(
        &bed.repo,
        &mut bed.git_resources,
        &mut bed.scan_resources,
        &mut bed.cache,
        &bed.snapshot,
        None,
        Adapter::Markdown,
        &document,
        false,
        "{includedir}/shared.adoc",
    )
    .expect("resolution")
    .1;
    assert!(
        matches!(markdown, Resolution::Missing(Missing::PathNotFound { .. })),
        "only AsciiDoc substitutes attributes into a destination",
    );
}

#[test]
fn the_asciidoc_destinations_no_tree_can_answer_are_declared() {
    let mut bed = bed();
    let document = RepoPath::new("docs/index.md".to_owned()).expect("document path");
    for (destination, is_image) in [
        ("img/logo.png", true),
        ("{includedir}/shared.adoc", false),
        ("some-page-identity", false),
        ("some-page-identity#section", false),
    ] {
        let row = resolve(
            &bed.repo,
            &mut bed.git_resources,
            &mut bed.scan_resources,
            &mut bed.cache,
            &bed.snapshot,
            None,
            Adapter::AsciiDoc,
            &document,
            is_image,
            destination,
        )
        .expect("resolution")
        .1;
        assert!(
            matches!(
                row,
                Resolution::UnsupportedSemantics(UnsupportedSemantics::AttributeDependent)
            ),
            "{destination} was not declared, got {row:?}",
        );
    }
}
