[package]
name = "amiss-wire"
version.workspace = true
edition.workspace = true
description = "Shared typed machine contracts of Amiss"
license.workspace = true
repository.workspace = true
exclude.workspace = true

[lib]
bench = false

[dependencies]
percent-encoding.workspace = true
countio.workspace = true
digest-io.workspace = true
hex.workspace = true
hex_fmt.workspace = true
json-serde.workspace = true
js_int.workspace = true
serde.workspace = true
serde-transcode.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
serde_json_canonicalizer.workspace = true
serde_path_to_error.workspace = true
serde_with = { workspace = true, features = ["std"] }
sha2.workspace = true
strum.workspace = true
thiserror.workspace = true
wary.workspace = true

[dev-dependencies]
divan.workspace = true
strum.workspace = true

[[bench]]
name = "wire"
harness = false

[lints]
workspace = true
