[package]
name = "amiss-fixtures"
version.workspace = true
edition.workspace = true
description = "Shared test fixtures for the Amiss workspace"
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
amiss-wire = { path = "../amiss-wire", version = "0.22.0" }
flate2.workspace = true
sha1-checked.workspace = true
tempfile.workspace = true

[lints]
workspace = true
