[package]
name = "amiss-md"
version.workspace = true
edition.workspace = true
description = "Document parsers for Amiss, pinned to the CommonMark and GFM corpora"
license.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
amiss-wire = { path = "../amiss-wire", version = "0.32.2" }
linkify = "0.11"
markdown = "1"
pulldown-cmark = { version = "0.13.4", default-features = false }

[dev-dependencies]
pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
sha2.workspace = true

[lints]
workspace = true
