[package]
name = "amiss-rst"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "reStructuredText reference extraction for the amiss documentation scanner"
exclude.workspace = true

[dependencies]
amiss-wire = { path = "../amiss-wire", version = "0.25.0" }

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "directive"
harness = false

[[bench]]
name = "extraction"
harness = false

[lints]
workspace = true
