[package]
name = "amiss-rst"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "reStructuredText reference extraction for the amiss documentation scanner"
exclude.workspace = true

[lints]
workspace = true
