use js_int::UInt;
use json_serde::deserialize_some;
use serde::{Deserialize, Serialize};

use super::metadata::{
    MergeCommitMessage, MergeCommitTitle, RepositoryPermissions, SquashMergeCommitMessage,
    SquashMergeCommitTitle,
};

#[serde_with::apply(Option<_> => #[serde(
    default,
    deserialize_with = "deserialize_some",
    skip_serializing_if = "Option::is_none"
)])]
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TemplateRepository {
    pub allow_auto_merge: Option<bool>,
    pub allow_merge_commit: Option<bool>,
    pub allow_rebase_merge: Option<bool>,
    pub allow_squash_merge: Option<bool>,
    pub allow_update_branch: Option<bool>,
    pub archive_url: Option<String>,
    pub archived: Option<bool>,
    pub assignees_url: Option<String>,
    pub blobs_url: Option<String>,
    pub branches_url: Option<String>,
    pub clone_url: Option<String>,
    pub collaborators_url: Option<String>,
    pub comments_url: Option<String>,
    pub commits_url: Option<String>,
    pub compare_url: Option<String>,
    pub contents_url: Option<String>,
    pub contributors_url: Option<String>,
    pub created_at: Option<String>,
    pub default_branch: Option<String>,
    pub delete_branch_on_merge: Option<bool>,
    pub deployments_url: Option<String>,
    pub description: Option<String>,
    pub disabled: Option<bool>,
    pub downloads_url: Option<String>,
    pub events_url: Option<String>,
    pub fork: Option<bool>,
    pub forks_count: Option<UInt>,
    pub forks_url: Option<String>,
    pub full_name: Option<String>,
    pub git_commits_url: Option<String>,
    pub git_refs_url: Option<String>,
    pub git_tags_url: Option<String>,
    pub git_url: Option<String>,
    pub has_downloads: Option<bool>,
    pub has_issues: Option<bool>,
    pub has_pages: Option<bool>,
    pub has_projects: Option<bool>,
    pub has_wiki: Option<bool>,
    pub homepage: Option<String>,
    pub hooks_url: Option<String>,
    pub html_url: Option<String>,
    pub id: Option<UInt>,
    pub is_template: Option<bool>,
    pub issue_comment_url: Option<String>,
    pub issue_events_url: Option<String>,
    pub issues_url: Option<String>,
    pub keys_url: Option<String>,
    pub labels_url: Option<String>,
    pub language: Option<String>,
    pub languages_url: Option<String>,
    pub merge_commit_message: Option<MergeCommitMessage>,
    pub merge_commit_title: Option<MergeCommitTitle>,
    pub merges_url: Option<String>,
    pub milestones_url: Option<String>,
    pub mirror_url: Option<String>,
    pub name: Option<String>,
    pub network_count: Option<UInt>,
    pub node_id: Option<String>,
    pub notifications_url: Option<String>,
    pub open_issues_count: Option<UInt>,
    pub owner: Option<TemplateOwner>,
    pub permissions: Option<RepositoryPermissions>,
    pub private: Option<bool>,
    pub pulls_url: Option<String>,
    pub pushed_at: Option<String>,
    pub releases_url: Option<String>,
    pub size: Option<UInt>,
    pub squash_merge_commit_message: Option<SquashMergeCommitMessage>,
    pub squash_merge_commit_title: Option<SquashMergeCommitTitle>,
    pub ssh_url: Option<String>,
    pub stargazers_count: Option<UInt>,
    pub stargazers_url: Option<String>,
    pub statuses_url: Option<String>,
    pub subscribers_count: Option<UInt>,
    pub subscribers_url: Option<String>,
    pub subscription_url: Option<String>,
    pub svn_url: Option<String>,
    pub tags_url: Option<String>,
    pub teams_url: Option<String>,
    pub temp_clone_token: Option<String>,
    pub topics: Option<Vec<String>>,
    pub trees_url: Option<String>,
    pub updated_at: Option<String>,
    pub url: Option<String>,
    pub use_squash_pr_title_as_default: Option<bool>,
    pub visibility: Option<String>,
    pub watchers_count: Option<UInt>,
}

#[serde_with::apply(Option<_> => #[serde(
    default,
    deserialize_with = "deserialize_some",
    skip_serializing_if = "Option::is_none"
)])]
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TemplateOwner {
    pub avatar_url: Option<String>,
    pub events_url: Option<String>,
    pub followers_url: Option<String>,
    pub following_url: Option<String>,
    pub gists_url: Option<String>,
    pub gravatar_id: Option<String>,
    pub html_url: Option<String>,
    pub id: Option<UInt>,
    pub login: Option<String>,
    pub node_id: Option<String>,
    pub organizations_url: Option<String>,
    pub received_events_url: Option<String>,
    pub repos_url: Option<String>,
    pub site_admin: Option<bool>,
    pub starred_url: Option<String>,
    pub subscriptions_url: Option<String>,
    #[serde(rename = "type")]
    pub kind: Option<String>,
    pub url: Option<String>,
}
